import { fmt, fmtPct, colorVar } from '../utils/format';

const ALERT_ICONS = {
  NEW_OPPORTUNITY: '🆕',
  BREAKOUT: '🚀',
  BREAKDOWN: '📉',
  TARGET_HIT: '🎯',
  STOPLOSS_HIT: '🛑',
  CONFIDENCE_UPGRADE: '📈',
  CONFIDENCE_DOWNGRADE: '📉',
};

const ALERT_COLORS = {
  NEW_OPPORTUNITY: { background: 'var(--blue-bg)', border: '1px solid rgba(77,158,255,0.2)', color: '#85C0FF' },
  BREAKOUT: { background: 'var(--green-bg)', border: '1px solid var(--green-border)', color: '#5DDDBB' },
  BREAKDOWN: { background: 'var(--red-bg)', border: '1px solid var(--red-border)', color: '#FF8096' },
  TARGET_HIT: { background: 'var(--green-bg)', border: '1px solid var(--green-border)', color: '#5DDDBB' },
  STOPLOSS_HIT: { background: 'var(--red-bg)', border: '1px solid var(--red-border)', color: '#FF8096' },
  CONFIDENCE_UPGRADE: { background: 'var(--green-bg)', border: '1px solid var(--green-border)', color: '#5DDDBB' },
  CONFIDENCE_DOWNGRADE: { background: 'var(--amber-bg)', border: '1px solid rgba(239,159,39,0.25)', color: 'var(--amber)' },
};

function AlertRow({ alert }) {
  const style = ALERT_COLORS[alert.type] || ALERT_COLORS.NEW_OPPORTUNITY;
  const icon = ALERT_ICONS[alert.type] || '🔔';
  return (
    <div className="card-enter" style={{ ...styles.alert, ...style }}>
      <span style={styles.alertIcon}>{icon}</span>
      <span style={styles.alertMessage}>{alert.message}</span>
      <span className="num" style={styles.alertTime}>{new Date(alert.timestamp).toLocaleTimeString('en-IN')}</span>
    </div>
  );
}

// PRIORITY 6/4 — REAL-TIME ALERT DASHBOARD. Shows the actual alerts the
// backend's alert engine generated by comparing each scan against the
// previous one — NOT locally re-derived from buys/sells. An empty list here
// is the honest, correct state on a quiet day or right after a cold start,
// not a sign anything is broken.
export default function SignalsPanel({ scan, niftyQuote, bankNiftyQuote, vixQuote }) {
  const { alerts, fakeSpikesFiltered, lastScanCompletedAt, scanning } = scan;

  const niftyBullish = niftyQuote && niftyQuote.changePct >= 0;
  const bnBullish = bankNiftyQuote && bankNiftyQuote.changePct >= 0;
  const vixLevel = vixQuote ? vixQuote.price : null;

  const counts = (alerts || []).reduce((acc, a) => { acc[a.type] = (acc[a.type] || 0) + 1; return acc; }, {});

  return (
    <div>
      <div style={styles.note}>
        🔔 Real-time alerts from the backend's alert engine — generated by comparing each scan cycle against the previous one (new opportunities, confidence changes, breakouts/breakdowns, target/stoploss hits). Not locally guessed.
        {lastScanCompletedAt && ` Last scan: ${new Date(lastScanCompletedAt).toLocaleTimeString('en-IN')} IST.`}
      </div>

      <div style={styles.alertList}>
        {(alerts || []).length === 0 ? (
          <div style={styles.emptyState}>
            {scanning
              ? 'Scanning — alerts will appear here as the scan finds new opportunities or changes.'
              : (
                <>
                  <div style={{ fontWeight: 600, marginBottom: 6 }}>No new alerts right now — and that's the honest, correct state.</div>
                  <div>Alerts only fire on a genuine CHANGE between scans: a stock newly entering Top Opportunities, its confidence moving 8+ points, a direction flip, or hitting its target/stoploss. If nothing has changed since the last scan, there's nothing new to report — showing alerts anyway would mean making them up. Click "Rescan Now" on the Top Opportunities tab after some time has passed to check again.</div>
                </>
              )}
          </div>
        ) : (
          alerts.map((a, i) => <AlertRow key={`${a.symbol}-${a.type}-${a.timestamp}-${i}`} alert={a} />)
        )}
      </div>

      <div style={styles.twoCol}>
        <div style={styles.card}>
          <div style={styles.cardTitle}>Scanner Conditions — Live Market Check</div>
          <Row label="Nifty above prev. close" value={niftyQuote ? (niftyBullish ? `✓ Bullish ${fmtPct(niftyQuote.changePct)}` : `✗ Bearish ${fmtPct(niftyQuote.changePct)}`) : '--'} color={niftyQuote ? colorVar(niftyQuote.changePct) : undefined} />
          <Row label="BankNifty trend" value={bankNiftyQuote ? (bnBullish ? `✓ Bullish ${fmtPct(bankNiftyQuote.changePct)}` : `✗ Bearish ${fmtPct(bankNiftyQuote.changePct)}`) : '--'} color={bankNiftyQuote ? colorVar(bankNiftyQuote.changePct) : undefined} />
          <Row label="India VIX (fear gauge)" value={vixLevel ? `${fmt(vixLevel)} — ${vixLevel < 15 ? 'Low fear' : vixLevel < 20 ? 'Moderate' : 'High fear'}` : '--'} color={vixLevel ? (vixLevel < 15 ? 'var(--green)' : vixLevel < 20 ? 'var(--amber)' : 'var(--red)') : undefined} />
          <Row label="Fake spikes filtered this scan" value={String(fakeSpikesFiltered)} color="var(--text2)" />
        </div>

        <div style={styles.card}>
          <div style={styles.cardTitle}>Alert Breakdown This Scan</div>
          <Row label="New opportunities" value={String(counts.NEW_OPPORTUNITY || 0)} color="var(--blue)" />
          <Row label="Confidence upgrades" value={String(counts.CONFIDENCE_UPGRADE || 0)} color="var(--green)" />
          <Row label="Confidence downgrades" value={String(counts.CONFIDENCE_DOWNGRADE || 0)} color="var(--amber)" />
          <Row label="Breakouts / Breakdowns" value={String((counts.BREAKOUT || 0) + (counts.BREAKDOWN || 0))} color="var(--text2)" />
          <Row label="Target / Stoploss hits" value={String((counts.TARGET_HIT || 0) + (counts.STOPLOSS_HIT || 0))} color="var(--text2)" />
        </div>
      </div>
    </div>
  );
}

function Row({ label, value, color = 'var(--text)' }) {
  return (
    <div style={styles.row}>
      <span style={styles.rowLabel}>{label}</span>
      <span style={{ fontWeight: 600, color }}>{value}</span>
    </div>
  );
}

const styles = {
  note: { fontSize: 12, color: 'var(--text3)', background: 'var(--bg3)', borderRadius: 8, padding: '10px 13px', marginBottom: 16 },
  alertList: { marginBottom: 18 },
  alert: { display: 'flex', alignItems: 'center', gap: 10, padding: '12px 14px', borderRadius: 9, marginBottom: 8, fontSize: 13, lineHeight: 1.4 },
  alertIcon: { fontSize: 15 },
  alertMessage: { flex: 1 },
  alertTime: { fontSize: 11, opacity: 0.7, whiteSpace: 'nowrap' },
  emptyState: { fontSize: 13, color: 'var(--text3)', padding: '20px 16px', textAlign: 'center', background: 'var(--bg2)', borderRadius: 11, border: '1px solid var(--border)' },
  twoCol: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 },
  card: { background: 'var(--bg2)', border: '1px solid var(--border)', borderRadius: 11, padding: 16 },
  cardTitle: { fontSize: 11, fontWeight: 700, color: 'var(--text2)', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 12 },
  row: { display: 'flex', justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid var(--border)', fontSize: 13 },
  rowLabel: { color: 'var(--text2)' },
};
